### ISSUE TITLE
Add a new interface extending from RosiePresenter.View

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Rosie#3] opened 2015-11-20 10:42 UTC
Some of the views we have to implement have a loading state. We are going to create a ``RosiePresenter.ViewWithLoading`` interface with two methods: ``showLoading`` and ``hideLoading`` to avoid code duplicity in all the library client code related to this classes.

**Comment by luis-ibanez** [comment] 2016-06-01 09:19
I am looking at this, because I faced a similar problem in another project and would be good to help and at the same time to find a standard solution for this.

The first proposal of this issue was to add the LoadingPresenter with the ViewWithLoading interface, to implement the show/hide loading, given that is used in a lot of views. But then appear another situations that are also widely used like the ones that @pedrovgs suggest. 

I think there are 3 solutions to this:

1.- Create a lot small Views with a lot Presenters implementing each: 
- RosiePresenterWithLoading<T extends RosiePresenterWithLoading.View>
- RosiePresenterWithEmptyCase<T extends RosiePresenterWithEmptyCase.View>
- RosiePresenterWithError<T extends RosiePresenterWithError.View>
- RosiePresenterWithNoConnectionWarning<T extends RosiePresenterWithNoConnectionWarning.View>
etc...

The problem with this one is that we couldn't extend our presenter from more than once, we could implement more than one view on the view of our presenter, but then having the RosiePresenters won't have any utility.

So I think we can easily discard this one.

2.- Create a RosiePresenterWithSteroids <T extends RosiePresenterWithSteroids.View>
We put all the methods that we can think (show/hide loading, showError, showEmptyCase... ) in this PresenterWithSteroids, and its view.

The problem is to implement this class without wanting to use all its functionality, we may end with a lot of empty implementations in the View. We could solve this with default methods form Java 8 or a NullObjectPattern.

3.- We remove this extended classes, expand the sample with more BasePresenters to help the users to get code from there, and reduce the library classes.

What do you think?

**Comment by pedrovgs** [comment] 2016-06-02 16:39
I think the option number 3 is going to be the best one or at least the most flexible one. Thoughts @flipper83 @Serchinastico ?

**Comment by Serchinastico** [comment] 2016-06-02 16:52
Yup, I'd say option 3 is the way to go until we get mixins with Java 8.

**Comment by flipper83** [comment] 2016-06-02 17:03
option 3 is the good one for me too, because two is impossible for now.  and we can use any kind of composition. I have an idea, that it's have small getViews interfaces and can do something similar to.

getView(LoadingView.class).hideLoading(); or have a map for enums. and if your view have this interface implemented it, invoke it. Have this sense?

**Comment by pedrovgs** [comment] 2016-06-04 08:15
I prefer simple solutions for this case. Add the method to the View interface just if need it. IMHO documentation here is more interesting than code.

**Comment by flipper83** [comment] 2016-06-05 08:38
I was talking with @pedrovgs about have a module with addons, and add here some kind of interfaces with method that you can add to your view interfaces. Do you like the idea?

**Comment by luis-ibanez** [comment] 2016-06-20 09:10
I think that if you look for examples on the use the sample is self-explanatory enough , with the module of add-ons which solution would you implement? The PresenterWithSteroids? or just three or four cases? Is it not better just to add a couple of examples on the sample?

**Comment by JorgeCastilloPrz** [comment] 2016-07-30 11:12
Isn't this already done ? I was checking this [RosiePresenterWithLoading class](https://github.com/Karumi/Rosie/blob/master/rosie/src/main/java/com/karumi/rosie/view/loading/RosiePresenterWithLoading.java). 

I think adding more custom view contracts like the one defined in `RosiePresenterWithLoading` to the sample code would be enough. It is good to let users have some freedom to define their own view behaviors IMO. You are doing more than enough providing them with all the lifecycle linking / null view objects for this layer

**Comment by pedrovgs** [comment] 2016-08-01 07:36
Yeap @JorgeCastilloPrz you are right. I'm closing this issue.

**Closed by pedrovgs** 2016-08-01 07:36 UTC
Labels: enhancement
